### ISSUE TITLE
Is it possible to use Magic Gradients with the Splash Screen?

### ISSUE THREAD

**Issue by ScottishRoss** [mgierlasinski/MagicGradients#104]
I'm wondering if it's possible to use this method of creating gradients to be used on the splash screen. I've been able to successfully use this for my app background, but the splash screen looks off due to colour differences.

**Comment by bbenetskyy** [comment]
@ScottishRoss you may use a trick like [TravelMonkey](https://github.com/jfversluis/TravelMonkey). They don't register anything on app start and optimize startup process. Create a simple view which now used as a custom Splash Screen and make all hard work there.
