### ISSUE TITLE
CornerRadius in Xamarin Forms?

### ISSUE THREAD

**Issue by BenjaNapo** [mgierlasinski/MagicGradients#105]
Hi, I'm working on Xamarin Forms project and I replaced a simple gray BoxView with GradientView (red to green), but I noticed that the GradientView doesn't have the CornerRadius attribute like the BoxView? How can I resolve?

**Comment by bbenetskyy** [comment]
Hi @BenjaNapo, please take a look at #61 maybe this solution will meet your expectation.

**Comment by BenjaNapo** [comment]
Wow, thank you so much! I placed and adapted that code and it worked immediately. Btw I'm interested about that control 👌😁

**Comment by bbenetskyy** [comment]
I will create an issue with specification about planned control and add a link here later, so you can check when it will be added 😋
