### ISSUE TITLE
App Size boosted because of SkiaSharp

### ISSUE THREAD

**Issue by acuntex** [mgierlasinski/MagicGradients#106]
First thanks for this wonderful library. Works like charm and does more than you can dream of.

But there is one downside... The App size gets boosted extremely by SkiaSharp. (e.g. 5-6MB on Android)

I just wanted to start a short discussion about if it would be possible to somehow replace the few parts that use SkiaSharp.

Not that SkiaSharp is bad, but it's a big monolithic library and I'm sure MagicGradients just uses a small portion of the lib.

**Comment by mgierlasinski** [comment]
Hi @acuntex, glad you like it :) 

The idea was to have solid, performant and shared drawing library so we can focus only on gradients, calculations and css parsing. Having experience with SkiaSharp in the past it was natural choice. We could do all the stuff with native rendering like new Brushes but that would required much more time that we can spare for this project and it's not on our roadmap at this moment.

Looking at Uno Platform becomes more popular, we are considering some refactoring of Magic Gradients so we can easily swap between Forms and UWP API. As part of this process we may also do some more separation of rendering logic, we will see.
