### ISSUE TITLE
UWP.Shell Playground  errror after update to version 4,8  System.AccessViolationException  thrown in runtime

### ISSUE THREAD

**Issue by filipoff2** [mgierlasinski/MagicGradients#111]
Error thrown on runtime:

System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

![image](https://user-images.githubusercontent.com/15687714/91174779-0b9b2080-e6e0-11ea-95c6-dde1477472e4.png)
On 

https://github.com/filipoff2/MagicGradients/tree/issues/Add-UWP-to-playground-project-with-Xamarin-Forms-4-8

Version updated with last master runs on 4,5 forms and UWP native 
https://github.com/mgierlasinski/MagicGradients/compare/master...filipoff2:issues/Add-UWP-Playground-Project-45?expand=1

![image](https://user-images.githubusercontent.com/15687714/91175170-a8f65480-e6e0-11ea-9681-34f8eb962c33.png)

![image](https://user-images.githubusercontent.com/15687714/91175286-d8a55c80-e6e0-11ea-860a-881882ff8ac9.png)

**Comment by filipoff2** [comment]
https://github.com/mgierlasinski/MagicGradients/compare/master...filipoff2:issues/Add-UWP-to-playground-project-with-Xamarin-Forms-4-8?expand=1

**Comment by filipoff2** [comment]
on 4,5 it runs but some trace is done:
tion thrown at 0x751A43D2 in Playground.UWP.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
Exception thrown at 0x751A43D2 in Playground.UWP.exe: Microsoft C++ exception: EEMessageException at memory location 0x0893D808.
Exception thrown at 0x751A43D2 in Playground.UWP.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
Exception thrown at 0x751A43D2 in Playground.UWP.exe: Microsoft C++ exception: EEMessageException at memory location 0x0893D7C0.
Exception thrown at 0x751A43D2 in Playground.UWP.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
Exception thrown at 0x751A43D2 in Playground.UWP.exe: Microsoft C++ exception: EEMessageException at memory location 0x0893D7C0.
Exception thrown at 0x751A43D2 in Playground.UWP.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
Exception thrown at 0x751A43D2 in Playground.UWP.exe: Microsoft C++ exception: EEMessageException at memory location 0x0893D700.
Exception thrown at 0x751A43D2 in Playground.UWP.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
Exception thrown at 0x751A43D2 in Playground.UWP.exe: Microsoft C++ exception: EEMessageException at memory location 0x0893D868.
Exception thrown at 0x751A43D2 in Playground.UWP.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
Exception thrown at 0x751A43D2 in Playground.UWP.exe: Microsoft C++ exception: EEMessageException at memory location 0x0893D838.
Exception thrown at 0x751A43D2 in Playground.UWP.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
Exception thrown at 0x751A43D2 in Playground.UWP.exe: Microsoft C++ exception: EEMessageException at memory location 0x0893D808.
Exception thrown at 0x751A43D2 in Playground.UWP.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
Exception thrown at 0x751A43D2 in Playground.UWP.exe: Microsoft C++ exception: EEMessageException at memory location 0x0893D7C0.
Exception thrown at 0x751A43D2 in Playground.UWP.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
Exception thrown at 0x751A43D2 in Playground.UWP.exe: Microsoft C++ exception: EEMessageException at memory location 0x0893D7C0.
Exception thrown at 0x751A43D2 in Playground.UWP.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
Exception thrown at 0x751A43D2 in Playground.UWP.exe: Microsoft C++ exception: EEMessageException at memory location 0x0893D700.
Exception thrown at 0x751A43D2 in Playground.UWP.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
The thread 0x4614 has exited with code 0 (0x0).

**Comment by mgierlasinski** [comment]
@bbenetskyy @filipoff2 any updates on this?
