### ISSUE TITLE
Playground support for Dark Mode

### ISSUE THREAD

**Issue by bbenetskyy** [mgierlasinski/MagicGradients#121]
We should consider in two options:

№1 Set in `info.plist` information that apps can [use only `Ligth` mode](https://medium.com/@akshay.s.somkuwar/disable-dark-mode-in-ios-13-for-your-ios-app-c025b446d87b)

![image](https://user-images.githubusercontent.com/8330262/93706590-0aff7980-fb28-11ea-966b-5918ac0fb37d.png)
![image](https://user-images.githubusercontent.com/8330262/93706602-1d79b300-fb28-11ea-94ce-6e776f67406a.png)

№2 Or Fix colors when they looks wrong because in some places it looks nice with dark mode:

![image](https://user-images.githubusercontent.com/8330262/93706646-7f3a1d00-fb28-11ea-85dc-050c5d7177b1.png)
![image](https://user-images.githubusercontent.com/8330262/93706650-90832980-fb28-11ea-9d2c-921c15b56375.png)

**Comment by mgierlasinski** [comment]
I vote for option 2. Dark mode has to implemented in general, on UWP it also looks bad at the moment.
