### ISSUE TITLE
CSS radial gradient not working correctly.

### ISSUE THREAD

**Issue by mapanjwani** [mgierlasinski/MagicGradients#138]
I have a css gradient which is not working correctly in this. The center should be on top like this:
![css1](https://user-images.githubusercontent.com/6677435/101267946-27eb3680-3780-11eb-9016-29647f42973e.png)

But it is displaying like this:
![Screenshot_1607212875](https://user-images.githubusercontent.com/6677435/101267969-405b5100-3780-11eb-9f4e-1bbef5dd554d.png)

The css is as following:
"radial-gradient(217.1% 106.25% at 50% -16.92%, #05FFCD 0%, #4371D8 36.77%, #612DDD 83.41%, #702DE7 100%)"

Let me know if I should change something in css to resolve the issue.

Thanks.

**Comment by bbenetskyy** [comment]
Hi @mapanjwani, 

If you replace `217.1% 106.25% at` with `circle at` that will works:

![image](https://user-images.githubusercontent.com/8330262/101374302-48191380-38ae-11eb-8077-51ef6dbd4aed.png)


```css
radial-gradient(circle at 50% -16.92%, #05FFCD 0%, #4371D8 36.77%, #612DDD 83.41%, #702DE7 100%)
```

Please, let me know if it solves your problem and we can close this issue 😉

**Comment by mgierlasinski** [comment]
@mapanjwani CSS parser doesn't support custom size for radial gradient at the moment, you can use circle or ellipse as "named" shape. We will add this in next release.

**Comment by mapanjwani** [comment]
Fantastic, thanks a lot guys.
