### ISSUE TITLE
[Spec] Change repository structure

### ISSUE THREAD

**Issue by mgierlasinski** [mgierlasinski/MagicGradients#187]
### Rename structure of directories to:

:file_folder: Assets _(no changes)_
:file_folder: samples
- _GradientsApp (Xamarin.Native, to be added)_
- Playground _(possible renamed to GradientStudio?)_
- PlaygroundMaui _(needs rename, this will be Forms/MAUI)_
- MagicCrawler _(WPF app for downloading gradient CSS)_

:file_folder: Scripts _(no changes)_
:file_folder: src
- MagicGradients _(deprecated)_
- MagicGradients.Core
- MagicGradients.Forms
- MagicGradients.Forms.Skia
- MagicGradients.Forms.SkiaViews _(will be removed)_
- _MagicGradients.Native (to be added)_
- MagicGradients.Toolkit

:file_folder: tests
- _MagicGradients.Core.Tests (to be added)_
- MagicGradients.Tests
- MagicGradients.Benchmark

:memo: MagicGradients.Graphics.sln
:memo: MagicGradients.Library.slnf
:memo: MagicGradients.Playground.slnf
:memo: MagicGradients.sln

**Comment by bbenetskyy** [comment]
@mgierlasinski are those projects:

* MagicGradients.Tests
* MagicGradients.Benchmark

still valid? Maybe we need to remove them now?

**Comment by bbenetskyy** [comment]
The overall, proposed structure looks good 🤩 🥳  according to me

**Comment by mgierlasinski** [comment]
> 
> 
> @mgierlasinski are those projects:
> 
>     * MagicGradients.Tests
> 
>     * MagicGradients.Benchmark
> 
> 
> still valid? Maybe we need to remove them now?

`MagicGradients.Tests` is for `MagicGradients` which is still our main project, we can remove them both when new implementation for Maui.Grahpics will be ready. For Benchmark, there is a separate task:

https://github.com/mgierlasinski/MagicGradients/issues/100

It needs some love :cry:
