### ISSUE TITLE
Add UWP Playground Project

### ISSUE THREAD

**Issue by bbenetskyy** [mgierlasinski/MagicGradients#45]
A new Playground project should be added to UWP Target Plattform.

**Comment by filipoff2** [comment]
as sHELL don't work: 
https://github.com/xamarin/Xamarin.Forms/issues/9407#event-3061349219
can't do PR:
https://github.com/filipoff2/MagicGradients/tree/issues/Add-UWP-Playground-Project-45
here is proposal of binding to 
https://github.com/filipoff2/MagicGradients/commit/3be8c6b57204e2f07dde2eb31dff607eb3241ddd
