### ISSUE TITLE
Repaint when gradient properties are changing

### ISSUE THREAD

**Issue by mgierlasinski** [mgierlasinski/MagicGradients#53]
When angle, color stops or other properties are changing in runtime, notify renderer to repaint itself. This feature can give you ability to create **ANIMATED GRADIENTS** :scream:

**Comment by Pemmican-Pete** [comment]
I'm really enjoying MagicGradients. Do you picture this enhancement also allowing binding of the CssGradientSource? Perhaps it does already, and I just haven't figured out how. My goal is to create a set of user-controlled themes on my app.

**Comment by mgierlasinski** [comment]
Plan is to make all properties reacting on changes and triggering gradient repainting, it will include CssGradientSource as well.

**Comment by DevEddy** [comment]
Same here. I tried this but.. shouldn't `OnPropertyChanged` be executed when Binding to e.g Color in `GradientStop`?
```csharp         
protected override void OnPropertyChanged([CallerMemberName] string propertyName = null)
 ```
- Eddy

**Comment by mgierlasinski** [comment]
@DevEddy There is an active PR related to CSS binding: https://github.com/mgierlasinski/MagicGradients/pull/64

It will not solve problem with repainting after XAML changes but it's a good start :)

**Comment by mgierlasinski** [comment]
@DevEddy PR with repainting was just merged, you can check it out if you want. There are also some first attempts to animate gradients, samples as always in Magic Playground :)

**Comment by DevEddy** [comment]
@mgierlasinski I just tried it and it works like expected, good work! 
Thanks!

-- Eddy
