### ISSUE TITLE
How to set Gradient background for all content pages

### ISSUE THREAD

**Issue by Edgaras91** [mgierlasinski/MagicGradients#54]
How to set a gradient background for ALL content pages in the app?

**Comment by Edgaras91** [comment]
What i've tried:
 <Style TargetType="ContentPage"  ApplyToDerivedTypes="True">
                <Setter Property="BackgroundColor">
                    <Setter.Value>
                        <magic:GradientView VerticalOptions="FillAndExpand">
                            <magic:GradientView.GradientSource>
                                <magic:LinearGradient Angle="45">
                                    <magic:GradientStop Color="#9E3A6F" Offset="0" />
                                    <magic:GradientStop Color="#3B1159" Offset="1" />
                                </magic:LinearGradient>
                            </magic:GradientView.GradientSource>
                        </magic:GradientView>
                    </Setter.Value>
                </Setter>
            </Style>

**Comment by mgierlasinski** [comment]
@Edgaras91 You need to create `GradientView` on each page and style it with xaml or css. One way is to create control template somewhere in resources:

```
<ControlTemplate x:Key="PageWithGradient">
	<Grid>
		<magic:GradientView VerticalOptions="FillAndExpand">
			<magic:GradientView.GradientSource>
				<magic:LinearGradient Angle="45">
					<magic:GradientStop Color="#9E3A6F" Offset="0" />
					<magic:GradientStop Color="#3B1159" Offset="1" />
				</magic:LinearGradient>
			</magic:GradientView.GradientSource>
		</magic:GradientView>
		<ContentPresenter />
	</Grid>
</ControlTemplate>
```

and then use it with page:

```
<ContentPage ControlTemplate="{StaticResource PageWithGradient}">
	...
</ContentPage>
```
You can also create some kind of `BasePage` and define template inline, you can see example of that [here](https://github.com/mgierlasinski/FormsPageTemplate/blob/master/FormsPageTemplate/Pages/BasePage.xaml).

Please let me know if that helped, I can create some example later today.

PS. Code samples were only compiled in my head, there might be mistakes :)

**Comment by Edgaras91** [comment]
I will try this and get back to you.

**Comment by Edgaras91** [comment]
That worked.

I wish there was a global way to set this for all pages, without modifying each page.
If you know how to achieve this, then please comment, if not, then you can close this question.

Thank you!

**Comment by mgierlasinski** [comment]
You can mix both solutions and put ControlTemplate to a global style:

```
<Style TargetType="ContentPage" ApplyToDerivedTypes="True">
  <Setter Property="ControlTemplate">
    <Setter.Value>
      <ControlTemplate>
        <Grid>
          <magic:GradientView VerticalOptions="FillAndExpand">
            <magic:GradientView.GradientSource>
              <magic:LinearGradient Angle="45">
                <magic:GradientStop Color="#9E3A6F" Offset="0" />
                <magic:GradientStop Color="#3B1159" Offset="1" />
              </magic:LinearGradient>
            </magic:GradientView.GradientSource>
          </magic:GradientView>
          <ContentPresenter />
        </Grid>
      </ControlTemplate>      
    </Setter.Value>
  </Setter>
</Style>
```
