### ISSUE TITLE
Unexpected behavior for repeating-linear-gradient

### ISSUE THREAD

**Issue by bbenetskyy** [mgierlasinski/MagicGradients#59]
```css
repeating-linear-gradient(45deg, hsla(54,0%,88%,0.05) 0px, hsla(54,0%,88%,0.05) 45px,hsl(224,72%,31%) 45px, hsl(224,72%,31%) 50px)
```
This CSS Should show something like this:

![image](https://user-images.githubusercontent.com/8330262/71964987-0ba4e980-31ff-11ea-9f41-ae570baa4267.png)

Right now it shows only white color.

**Comment by bbenetskyy** [comment]
You can test it on: https://css-playground.com/view/45/css-gradient-playground

**Comment by mgierlasinski** [comment]
Fixed in https://github.com/mgierlasinski/MagicGradients/pull/70
