### ISSUE TITLE
Add Complex Grid CSS Exaplmes

### ISSUE THREAD

**Issue by bbenetskyy** [mgierlasinski/MagicGradients#60]
We should import new examples from https://www.gradientmagic.com/collection/complexgrid

**Comment by mgierlasinski** [comment]
With regular expression:
`<div class="body" style="background-image: *(.+?)">`

We can easily extract css from static html page. Get `group[1]` for gradient code (`group[0]` is the whole match).

**Comment by bbenetskyy** [comment]
New App to parse Gradients is done, now will go PR's with new Gradients for Playground App 😉
