### ISSUE TITLE
Add Splash Screen

### ISSUE THREAD

**Issue by bbenetskyy** [mgierlasinski/MagicGradients#65]
I would like to propose a new  Splash Screen for our Playground app, right now it's just a blank screen.

@mgierlasinski & @filipoff2 please, take a look at the next propositions from me and left a comment which looks the best for you.

<div>
<img src="https://user-images.githubusercontent.com/8330262/76163244-d35d5100-6144-11ea-9b39-5f4a96f2049d.png" width="200"/>

<img src="https://user-images.githubusercontent.com/8330262/76163246-d48e7e00-6144-11ea-883e-b9643bbc8316.png" width="200"/>

<img src="https://user-images.githubusercontent.com/8330262/76163245-d48e7e00-6144-11ea-8171-445d361b719d.png" width="200"/>
</div>

From my side - I propose the first one Splash Screen(Xamarin_1)

**Comment by mgierlasinski** [comment]
They are nice but none of them has anything related to gradients :) First one is ok but it's not very practical for Android where positioning image is quite limited (if we are using splash without layout file).  Maybe something with our magic wand as a logo would more adequate.

**Comment by mgierlasinski** [comment]
@bbenetskyy What about this?

**Comment by bbenetskyy** [comment]
I don't have q new good Splash Screen yet. When I will have it - I will propose it here 😉

**Comment by bbenetskyy** [comment]
@mgierlasinski  with animations at Magic Gradients we could create a splash screen with one of them, for example:

![img](https://media.giphy.com/media/cAIybJYwWeGTdIgzR6/giphy.gif)
