### ISSUE TITLE
Update ReadMe file

### ISSUE THREAD

**Issue by bbenetskyy** [mgierlasinski/MagicGradients#67]
# We need to update our main ReadMe.md file

We need to:

- Remove old gifs
- Remove Old Photos 
- Add New Gifs with new features
- More New Screenshots from Playground App
- Record new video for YouTube
- Re-organize readme sections if it will be needed

Also we need to:

- Update Repo Project Details
- Update Milestone Details

**Comment by mgierlasinski** [comment]
We need smaller but higher quality gif and more images of playground. Link to YT is very optional, first seconds of looking at pretty images in readme is critical, people usually don't click any links.

**Comment by mgierlasinski** [comment]
No update since a year, closing.
