### ISSUE TITLE
Add Possibility to test Gradients on Real Controls

### ISSUE THREAD

**Issue by bbenetskyy** [mgierlasinski/MagicGradients#68]
# We need to create a new Page where we could apply selected gradient and see how it will look in real controls

For example:

- Button with Gradient Background
- Page Background
- Move Cool Elements on a Page(Add in comments to this issue)
- Customization of That elements

**Comment by bbenetskyy** [comment]
It's how it looks right now
![Alt Text](https://media.giphy.com/media/PhU0sn7cpdQsUA1L1q/giphy.gif)

**Comment by bbenetskyy** [comment]
Connected PR is merged but we need to record Gif for this new feature and write a blog post

**Comment by mgierlasinski** [comment]
We already have task for updating docs: #https://github.com/mgierlasinski/MagicGradients/issues/67

**Comment by bbenetskyy** [comment]
yeah 😄 , so we can close this issue then
