### ISSUE TITLE
GradientView does not accept direct content

### ISSUE THREAD

**Issue by nodoid** [mgierlasinski/MagicGradients#71]
I've installed the nuget release into my forms project and have added the required xmlns line to the top of my xaml page.

Using the playground example for a straight linear gradient, I'm getting an errror that the gradientview does not accept direct content

Visual Studio Community 2019 for Mac (Preview)
Version 8.6 Preview (8.6 build 3437)
MagiGradients 1.0.0
Xam.Forms 4.5.0530

**Comment by bbenetskyy** [comment]
Hi @nodoid, I want to check what's going wrong in your project. Could you send me part of the XAML code that you have used in your view, please?

**Comment by mgierlasinski** [comment]
@nodoid using direct content is already implemented, you can use if you build source from master branch, it was not released yet as a nuget. We plan to publish new version in next days.

**Comment by mgierlasinski** [comment]
Implemented in version 1.1.0.
