### ISSUE TITLE
How to add Gradients on the Shell TabBar

### ISSUE THREAD

**Issue by bbenetskyy** [mgierlasinski/MagicGradients#81]
Question from Aziz at Medium Blog Post: 
`Is it possible to use MagicGradients on the shell TabBar? I want to have a gradient background set for the navigation bar and the bottom tabbar.`

### Here we just need to give an answer with sample code

**Comment by mgierlasinski** [comment]
@bbenetskyy Any updates on this?

**Comment by mgierlasinski** [comment]
@bbenetskyy Ok so I will respond to myself :) `GradientView` is Forms control and can't be use on native `TabBar` which is rendered on shell. Custom `TabBar` was planned for forms but it has been cut. There are also several Nugets in progress that may have it in the future:

https://github.com/xamarin/XamarinCommunityToolkit
https://github.com/jsuarezruiz/TemplateUI

Closing issue.
