### ISSUE TITLE
iOS Deploy to device

### ISSUE THREAD

**Issue by mrbmz** [mgierlasinski/MagicGradients#84]
It seems that using an older version of XCode (10.1) my application can't deploy to an IOS 13 device once I start using MagicGradients. (Based on research of the error).

It's such a shame because my app is almost done and there hasn't been any other problems or incompatibilities with other frameworks. As soon as I put this sample snippet into a XAML page I get the error that follows. If I take that out it deploys to my device with no errors (even though the Nuget packages are still installed and referenced). 

<magic:GradientView VerticalOptions="FillAndExpand">
     <magic:GradientView.GradientSource>
         <magic:LinearGradient Angle="90">
             <magic:GradientStop Color="Red" Offset="0" />
             <magic:GradientStop Color="Yellow" Offset="1" />
         </magic:LinearGradient>
     </magic:GradientView.GradientSource>
 </magic:GradientView>

Error:  error MT4109: Failed to compile the generated registrar code.

Same code and app will deploy to an IOS Simulator without issue. 

Hoping maybe someone knows what the cause is and I can perhaps still use this in my application.

**Comment by mgierlasinski** [comment]
@mrbmz It looks like generic problem with version mismatch between XCode/Xamarin.iOS/VS. What version of Xamarin.iOS you have installed? Which version of Visual Studio?

**Comment by mgierlasinski** [comment]
@mrbmz Any updates on this? If no, I will close the issue.
