### ISSUE TITLE
Icons missed on iOS

### ISSUE THREAD

**Issue by Dexteri** [mgierlasinski/MagicGradients#86]
![image](https://user-images.githubusercontent.com/12136523/82928062-f5b37d80-9f81-11ea-92d9-de8160f7ac2d.png)

**Comment by bbenetskyy** [comment]
In the weekend we will fix it

**Comment by mgierlasinski** [comment]
@Dexteri Thanks for reporting. @bbenetskyy maybe it's a good moment to use new Embedded Fonts? When Playground was created this feature was not there yet 😊

**Comment by bbenetskyy** [comment]
Yes! You are reading my mind 😉
