### ISSUE TITLE
How to apply gradients to UI when generated in C# code-behind?

### ISSUE THREAD

**Issue by jez9999** [mgierlasinski/MagicGradients#92]
The README gives an example of generating gradients in code:

```
 var gradients = new GradientBuilder()
    .AddLinearGradient(45)
        .AddStop(Color.Green, 0.2f)
        .AddStop(Color.Aqua, 0.9f)
    .AddLinearGradient(90)
        .AddStop(Color.Blue)
        .AddStop(Color.DeepPink)
    .Build();
```

However, how do you then use the `gradients` array?  I can't find any way to use it to set background gradients for elements in my Xamarin app.  I think the README should be updated to clarify this.

**Comment by jez9999** [comment]
@mgierlasinski And how do you get a reference to `gradientView`?

**Comment by mgierlasinski** [comment]
You can add `x:Name="myGradientView"` in Xaml to access in Page code behind. In View Model you can add property of type `GradientCollection` and bind to `GradientSource` property of `GradientView`.

**Comment by jez9999** [comment]
I've got it working. Thanks. As you said, a documentation update would be useful.
