### ISSUE TITLE
Set canvas size regardless of container size?

### ISSUE THREAD

**Issue by jez9999** [mgierlasinski/MagicGradients#93]
Is there a way to set the canvas size for a GradientView to something other than the container size?  We're displaying a background to our chats, and the GradientView initially has a height of nearly the full screen.  However, when the keyboard is brought up, it resizes the container ContentPage to being much shorter, which causes the gradient to get rendered differently.  What we want to do is keep the rendering canvas height/width the same as it was initially set to.

I've tried setting GradientView.HeightRequest, but this doesn't seem to be able to make the height larger than that of the container.

**Comment by mgierlasinski** [comment]
@jez9999 Maybe you could try putting `GradientView` into `AbsoluteLayout` and set correct `AbsoluteLayout.LayoutBounds` and `AbsoluteLayout.LayoutFlags` for `GradientView`?

**Comment by jez9999** [comment]
> 
> 
> @jez9999 Maybe you could try putting `GradientView` into `AbsoluteLayout` and set correct `AbsoluteLayout.LayoutBounds` and `AbsoluteLayout.LayoutFlags` for `GradientView`?

Is it possible to then overlay the existing UI on top of that background?  Because we do want the existing UI to resize when the keyboard is brought up, but we want the background not to.

**Comment by mgierlasinski** [comment]
@jez9999 Play around with layout settings. You may also want to check soft keyboard behavior:
https://guides.codepath.com/android/Working-with-the-Soft-Keyboard
