### ISSUE TITLE
Fix Complex Patterns Category

### ISSUE THREAD

**Issue by bbenetskyy** [mgierlasinski/MagicGradients#96]
In Playground App we have hidden `Complex Patterns` category with not supported for a moment CSS Code.

After #95 will be merged we should go and provide proper changes for gradients in `Complex Patterns` Category and add it into Playground database at `Matadata.json` and insert with name and slug into `Categories.json` file.

**Comment by mgierlasinski** [comment]
Without #95 you should be able to fix Gradient Parser for background-size in CSS, now we have:
```
{
    "slug": "b79936eb-215b-4d46-801d-800e7057bf3e",
    "stylesheet": "repeating-radial-gradient(...)52px 52px", // this is bad
    "tags": [ "complexpatterns" ]
  },
```
change to:
```
{
    "slug": "b79936eb-215b-4d46-801d-800e7057bf3e",
    "stylesheet": "repeating-radial-gradient(...)",
    "size": "52px 52px",
    "tags": [ "complexpatterns" ]
  },
```
Later, when we have #95, we can read "size".

**Comment by mgierlasinski** [comment]
@bbenetskyy Are there still issues with rendering after latest updates?

**Comment by bbenetskyy** [comment]
In the latest Playground DB this looks fine
