### ISSUE TITLE
Check  Simple Patterns Category

### ISSUE THREAD

**Issue by bbenetskyy** [mgierlasinski/MagicGradients#97]
We should Check how Gradients from `Simple Patterns` draw at [CSS-Gradient-Playgroud](https://css-playground.com/view/45/css-gradient-playground) and ensure that all looks in the same way, otherwise we should:

* Fix Them 
* Or Add Proper Issue for `Magic Gradients` Core Project with a description of non-working changes

**Comment by mgierlasinski** [comment]
If there are gradients that look different in Playground compared to website, please paste here one sample to see what CSS we are trying to parse and render.

**Comment by mgierlasinski** [comment]
@bbenetskyy Are there still issues with rendering after latest updates?

**Comment by bbenetskyy** [comment]
In the latest Playground DB this looks fine
