### ISSUE TITLE
Check Gingham Category

### ISSUE THREAD

**Issue by bbenetskyy** [mgierlasinski/MagicGradients#98]
This `Gingham` Category contains strange transformations while resisting. We may consider about a blog post with a solution for them and provide proper fixes in the `Playground` App.

**Comment by mgierlasinski** [comment]
What transformations you mean? Paste here a sample, maybe we can make adjustment to parser/rendering instead of manually fixing css.

**Comment by mgierlasinski** [comment]
@bbenetskyy Are there still issues with rendering after latest updates?

**Comment by bbenetskyy** [comment]
In the latest Playground DB this looks fine
