### ISSUE TITLE
Check Uneven Diamonds Category

### ISSUE THREAD

**Issue by bbenetskyy** [mgierlasinski/MagicGradients#99]
We should Check how Gradients from `Uneven Diamonds` draw at [CSS-Gradient-Playgroud](https://css-playground.com/view/45/css-gradient-playground) and ensure that all looks in the same way, otherwise we should:

* Fix Them 
* Or Add Proper Issue for `Magic Gradients` Core Project with a description of non-working changes

**Comment by mgierlasinski** [comment]
@bbenetskyy Are there still issues with rendering after latest updates?

**Comment by bbenetskyy** [comment]
In the latest Playground DB this looks fine
